name: CI

"on":
  merge_group: {}
  pull_request: {}
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    # (optional) only build on tags or ticket branches
    if: >
      startsWith(github.ref, 'refs/tags/')
      || startsWith(github.head_ref, 'tickets/')

    steps:
      - uses: actions/checkout@v3

      - uses: lsst-sqre/build-and-push-to-ghcr@v1
        id: build
        with:
          image: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          context: ./docker
          dockerfile: ./docker/Dockerfile

      - name: Push latest tag on main
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Tagging image as latest"
          docker tag ghcr.io/${{ github.repository }}:${{ steps.build.outputs.tag }} ghcr.io/${{ github.repository }}:latest
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/${{ github.repository }}:latest

      - run: echo Pushed ghcr.io/${{ github.repository }}:${{ steps.build.outputs.tag }}